#!/usr/bin/env php
<?php
	/**
	 * this file will be only accessed trhough the console
	 * if you pass the parameter install to it, it will
	 * create the SQLite database, start it, and try to
	 * create shortcuts, allowing the use of the comand
	 * mind, in your console
	 */

	$_MIND= Array();
	$_MIND['env']= 'shell';

	// checks if it has received any argument
	if(sizeOf($_SERVER['argv'])>0)
	{
		// installation should create the required SQLite database and a shortcut command
		if($_SERVER['argv'][1] == 'install')
		{
			// first, for linux and mac computers
			if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN')
			{
				require('mind3rd/env/setup/UnixSetup.php');
				UnixSetup::install();
			}else{
					WinSetup::install();
				 }
			exit;
		}
		// if not installing, it should be redirected to mind3rd/API/shell.php
		include('location:./mind3rd/API/shell.php');
	}