<?php
	class SQLServer implements sgbdInterface
	{
		public $attType= Array();
		public function __construct()
		{
			$this->attType= Array();
			$this->attType['key']		= "int IDENTITY(1,1) NOT NULL";
			$this->attType['varchar']	= "varchar(<length>)";
			$this->attType['char']		= "char(<length>)";
			$this->attType['text']		= "text";
			$this->attType['date']		= "datetime";
			$this->attType['blob']		= "varbinary(MAX)";
			$this->attType['integer']	= "int";
			$this->attType['bigint']	= "bigint";
			$this->attType['smallint']	= "smallint";
			$this->attType['int']		= "int";
			$this->attType['time']		= "timestamp";
			$this->attType['dateTime']	= "timestamp";
			$this->attType['float']		= "float";
			$this->attType['boolean']	= "tinyint";
			$this->attType['serial']	= "IDENTITY(1,1)";
		}
		public function header()
		{
			return "<mindComment>/*####################################################</mindComment>
<mindComment>#   Generated by Mind                                #</mindComment>
<mindComment>#   Developed by Felipe Nascimento de Moura / 2008   #</mindComment>
<mindComment>#   Generate MS SqlServer DataBase SQLs              #</mindComment>
<mindComment>######################################################*/</mindComment>
<obj>USE</obj> <element><databasename></element>;
";
		}
		
		public function createConnection()
		{
			return "function connectToSqlServer()
					{
						\$connection= mssql_connect('<host>:<port>', '<user>', '<pwd>');
						\$db_selected = mssql_select_db('<dbname>', \$this->connection);
						return \$connection;
					}";
		}
		public function query($dbCon, $qr)
		{
			$qr= preg_split('/\/\* SQL: table .*\*\//', $qr);
			for($i=1; $i<count($qr); $i++)
			{
				echo $qr[$i];
				$ExecutedQuery= mssql_select_db($qr[$i], $dbCon);
				if(!$ExecutedQuery)
				{
					return false;
				}
			}
			return true;
		}
		public function createDesconnection()
		{
			return  "mssql_close(\$this->connection)";
		}
		
		public function createDefaultValue()
		{
			return "default (<defaultvalue>)";
		}
		public function createSchema()
		{
			return "";
		}
		public function createField()
		{
			return "<element><fieldname></element> <fieldtype> <allownull> <serialvalue>";
		}
		public function createFieldComment()
		{
			return "";
		}
		public function createTableComment()
		{
			return "";
		}
		public function createFK()
		{
			return "<constructor>FOREIGN KEY</constructor>(<element><foreignkey></element>) <obj>REFERENCES</obj> <element><references>(<primarykeys>)</element>";
		}
		public function defaultPrimaryKey()
		{
			return "int(8, NULL, auto_increment)";
			//return "int IDENTITY(1,1) NOT NULL";
			//return "int(8, NULL, IDENTITY )";
		}
		public function createPK()
		{
			return "<obj>PRIMARY KEY</obj>(<element><primarykeys></element>)";
		}
		public function createTable()
		{
			return "	<mindComment>/* SQL: table <tablename> */</mindComment>
<constructor>CREATE</constructor> <obj>TABLE</obj> <element><tablename></element>
<element>(</element>
<fieldnames>
<element>)</element>";
		}
	}
?>