<?php

namespace en;

require_once dirname(__FILE__) . '/../../../../../mind3rd/API/languages/en/IgnoreForms.php';

/**
 * Test class for IgnoreForms.
 * Generated by PHPUnit on 2011-02-08 at 21:47:15.
 */
class IgnoreFormsTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var IgnoreForms
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new IgnoreForms;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	public function testShouldBeIgnored() {
		$this->assertTrue(IgnoreForms::shouldBeIgnored('whom'));
	}

	public function testShouldBeIgnored2() {
		$this->assertTrue(IgnoreForms::shouldBeIgnored('well'));
	}

	public function testShouldBeIgnored3() {
		$this->assertTrue(IgnoreForms::shouldBeIgnored('monthly'));
	}

	public function testShouldBeIgnored4() {
		$this->assertTrue(IgnoreForms::shouldBeIgnored('currently'));
	}

	public function testShouldBeUsed() {
		$this->assertTrue(IgnoreForms::shouldBeUsed('year'));
	}
	public function testShouldBeUsed2() {
		$this->assertTrue(IgnoreForms::shouldBeUsed('month'));
	}
	public function testShouldBeUsed3() {
		$this->assertTrue(IgnoreForms::shouldBeUsed('now'));
	}

}