<h3>Zend Models has no advanced options.</h3>
<hr>
Instructions:<br>
The files will be generated by default at <i>users/&lt;username>/temp/&lt;project name>/root/</i> <br>
You must have  the Zend Framework (<a href='http://www.zend.com/community/downloads'>http://www.zend.com/community/downloads</a>) in our localhost directory.<br>

