<?php
require(dirname(__FILE__) . '/../../../../../Tests/config.php');

/**
 * Test class for Tokenizer.
 * Generated by PHPUnit on 2011-02-21 at 11:46:35.
 */
class TokenizerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Tokenizer
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		Mind::$currentProject['idiom']= 'en';
		Mind::$langPath= dirname(__FILE__) . '/../../../../../mind3rd/API/languages/';
		require_once dirname(__FILE__) . '/../../../../../mind3rd/API/languages/en/IgnoreForms.php';
		require_once dirname(__FILE__) . '/../../../../../mind3rd/API/languages/en/Verbalizer.php';
		Tokenizer::loadModifiers(dirname(__FILE__) . '/../../../../../mind3rd/API/languages/en/');
		$this->object = new Tokenizer;
		//$this->object->loadModifiers('../../languages/en/');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	public function testSweep1() {
		$ar= Array('each','teacher','must', 'have', 'one','or','many','student','.');
		$exp= Array(2, 2, 64, 1, 8, 16, 32, 2, -2);
		$this->assertEquals($this->object->sweep($ar), $exp);
	}
	public function testSweep2() {
		$ar= Array('teacher', 'have', 'one','student','.');
		$exp= Array(2, 1, 8, 2, -2);
		$this->assertEquals($this->object->sweep($ar), $exp);
	}

}