<?php	// starting configuration file
	header ('Content-type: text/html; charset=utf-8');
	
	$_MIND= Array();
	$_MIND['appName']				= 'theWebMind(s) - 2.0';
	$_MIND['wmlCurrentVersion']		= '1.0';
	$_MIND['home_page']				= 'http://latest.thewebmind.org/home.php'; //'http://latest.thewebmind.org/home.php';
	//$_MIND['home_page']				= 'http://localhost/thewebmind.org/latest/home.php';;
	$_MIND['updateSource']			= 'http://latest.thewebmind.org/current.xml';
	//$_MIND['updateSource']			= 'http://localhost/thewebmind.org/latest/current.xml';
	$_MIND['wmlVersion']			= Array();
	$_MIND['wmlVersion']['1.0']		= '<?wml version="1.0"?>';
	$_MIND['logDirectory']			= 'logs';
	$_MIND['cryptKey']				= 'theWebMind';
	$_MIND['header']				= 'components/header.php';		// the header to be loaded in each file
	$_MIND['components']			= 'components';					// the Mind components directory
	$_MIND['frameworkDir']			= 'framework';					// the framework directory
	$_MIND['framework']				= 'framework/mind-2.0.php';		// the framework to be loaded in each file
	$_MIND['sessionDir']			= 'default';					// aplies the default, or the specified directory to record sessions
	$_MIND['sessionLife']			= '0'; 							// the value in seconds, use "0" to end when the browser is closed
	$_MIND['userDir']				= 'users'; 						// directory to load user information
	$_MIND['userConfFile']			= 'conf'; 						// directory to load user information
	$_MIND['imageDir']				= 'images';						// directory to load images to Mind Interface
	$_MIND['scriptSrc']				= 'framework/scripts';			// directory to load scripts to Mind Interface
	$_MIND['styleSrc']				= 'framework/styles';			// directory to load CSS styles to Mind Interface
	$_MIND['themeSrc']				= 'framework/styles/themes';	// directory to load CSS styles to Mind Interface
	$_MIND['fwComponents']			= 'framework/components';		// components to be used by the mind framework
	$_MIND['dbmsDir']				= 'dbmss';						// directory to load DBMS configuration and libraries
	$_MIND['defaultDbms']			= 'postgres';
	$_MIND['default_timezone']		= 'America/Sao_Paulo';
	$_MIND['autoBackup']			= true;							// generates a copy of the current version of the system, before replacing it
	$_MIND['pluginDir']				= 'plugins';					// directory to load plugins
	$_MIND['moduleDir']				= 'modules';					// directory to load modules
	$_MIND['defaultModule']			= 'php_mvc';
	$_MIND['languageDir']			= 'languages';					// directory to load modules
	$_MIND['defaultLanguage']		= 'en';
	$_MIND['licenses']				= '../licenses';				// the directory where you will find the licenses
	$_MIND['docs']					= 'docs';						// the directory where you will find the documentation and help content
	$_MIND['allowExport']			= true;							// allows the user to export project information (when false, only admin can do it)
	$_MIND['rootDir']				= '';
	$_MIND['publishDir']			= 'projects';
	$_MIND['backupDir']				= '.MindBackUps';
	$_MIND['errorMessagesFile']		= 'messages/error.php';
	$_MIND['warningMessagesFile']	= 'messages/warning.php';
	$_MIND['tipMessagesFile']		= 'messages/tip.php';
	$_MIND['primaryKeyPrefix']		= 'pk_';
	$_MIND['foreignKeyPrefix']		= 'fk_';
	$_MIND['parentOnSelfRelation']	= 'main_';
	$_MIND['selfRelationalTable']	= '_pointer';
	$_MIND['showDeveloperMenu']		= false;						// shows the menu DEVELOPER, or not
	$_MIND['load']					= Array();
		$_MIND['load']['user'] 		= 'classes/user.php';
		$_MIND['load']['project']	= 'classes/project.php';
		$_MIND['load']['plugin']	= 'classes/plugin.php';
		$_MIND['load']['module']	= 'classes/module.php';
		// $_MIND['load']['extraConfig'] = 'myConfigFile.php'; 		//to load extra configuration of yours, to the system, it may be used by your own modules, or plugins that require so
	$_MIND['version']				= '2.0';
	$_MIND['year']					= '2010';
	$_MIND['month']					= '';
	$_MIND['mindSpecificInfoAt']	= 'http://thewebmind.org/';
	$_MIND['developers']			= 'http://code.google.com/p/webmind/people/list';